configuration:
  template_dir:
  - "mobans/templates"
  - ".moban.d"
  configuration: echarts-cities-js.yml
targets:
  - output: README.md
    template: custom_readme.md.jj2
    configuration: cities.yml
  - output: CHANGELOG.md
    configuration: changelog.yml
    template: changelog.md.jj2
 
